### ISSUE TITLE
Borked output when comparing PAKs

### ISSUE THREAD

**Issue by ghramsey** [Oliver2Goetz/AIPAKFileDifferentiation#8]
![Image](https://github.com/user-attachments/assets/5bfa8dec-a956-4bd6-857b-97360d60ebfc)

[WORLD.zip](https://github.com/user-attachments/files/19782025/WORLD.zip)

I'm not sure what is going on here.  

Recently the Commands.PAKs are being saved with an inflated file size. 
Matt said those are a result of writing more to them.

This might be related to the issue at hand.   Overtime the commands.pak changes cause the output of comparing
files to look like the screenshot. Obviously, something quite wrong.

Also, in listview if I click on some entities it throws an exception:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AIPAKDifferentiation.Views.TreeViewDetails.getCompositeDetails(TreeNodeEntry entry)
   at AIPAKDifferentiation.Views.TreeViewDetails.buildTreeViewDetails(TreeNodeEntry entry)
   at AIPAKDifferentiation.AIPAKDifferentiation.buildTreeViewDetails(TreeNodeEntry entry)
   at AIPAKDifferentiation.AIPAKDifferentiation.treeviewDifferences_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

==

Added Tech_Comms World folder and all currently saved files.

No emergency on this.  I know this is a hobby project.  
But I have a feeling that it's a bug at cathodelib level you might want to report.

**Comment by ghramsey** [comment]
Some added details on this: the issue seems to happen if I'm saving files on staging branch.
If I mix saving from staging or just staging alone it immediately breaks the output.
The master branch seems to be OK though.

**Comment by Oliver2Goetz** [comment]
Hey @ghramsey 
thanks for reporting and creating an issue.

1. - I will test this again once the a new master branch version is released. Doing code changes for OpenCAGE's staging branch doesn't seem too efficient. Maybe it'll get resolved by then. If not, I'll check what exactly changed for the update and see what I can do on my side.
For now, maybe you could save a fresh vanilla PAK and compare that with your modded file. This should only show the changes you made as differences.

2. - Do you remember on which entity/composite you clicked in the listview when the exception was thrown? I sadly cannot reproduce it.

**Comment by Oliver2Goetz** [comment]
Personal notes:
The composites which are listed are shown as DELTED and aftwards also CREATED. 

This (probably) caused by OpenCAGE, since the composite names are changed from all uppercase to a simple leading uppercase. Example:
```
[30-78-03-00] AYZ\FX_LIBRARY\DEBRIS\DEBRIS_16 (DELETED)
[30-78-03-00] AYZ\FX_Library\Debris\Debris_16 (CREATED)
```

reference: loadDifferencesComposites() -> L:52 + L:62
Probably need to change that to a shortGuid check. Should be more save anyway since it's unique but I have something in mind in which this broke something else. Maybe using a ToLower() or similar can be used.

**Comment by ghramsey** [comment]
Still happens now on Master Branch update from April 26th.    And confirms it's OpenCAGE at fault.

Here's output from same file before and after saving with current open cage. 
This is old Kitty's Nightmare for HospitalUpper Map.    I've made no changes in opencage.  The output is normal.

[AIPakDiff-Export SCI_HOSPITALUPPER 2025-04-27_9-21-53.txt](https://github.com/user-attachments/files/19930228/AIPakDiff-Export.SCI_HOSPITALUPPER.2025-04-27_9-21-53.txt)

This is the output after loading the same file and saving with opencage without any actual editing.  
The mere act of saving the file after loading does something internally to the structure it seems.

[AIPakDiff-Export SCI_HOSPITALUPPER 2025-04-27_9-23-28.txt](https://github.com/user-attachments/files/19930265/AIPakDiff-Export.SCI_HOSPITALUPPER.2025-04-27_9-23-28.txt)

**Comment by Oliver2Goetz** [comment]
The wrongly shown entries are not shown anymore. Fixed in the newest version: https://github.com/Oliver2Goetz/AIPAKFileDifferentiation/releases/tag/v0.7.2

> Also, in listview if I click on some entities it throws an exception: ...

If the issue with the exception still happens, please create a new issue for that.
I couldn't replicate that and even if, it might have been an issue with the entries which were wrongly shown anyway.
Thank you so much for reporting!
